version: '3.5'
 
 
services:
  postgres-user:
    container_name: postgres_user
    image: postgres:latest
    environment:
      POSTGRES_USER: kaka
      POSTGRES_PASSWORD: kakaka
      SCHAME: public
      POSTGRES_DB: manage_user
    volumes:
      - "./postgres_user/data:/var/lib/postgresql/data"
    command: -p 5433
    ports:
      - "31000:5433"
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: iam
      POSTGRES_PASSWORD: iam123456
      SCHEMA: public
      POSTGRES_DB: postgres
      #PGPASSWORD: iam123456
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "30000:5432"
  keycloak:
    container_name: keycloak_demo
    image: kc-custom-otp:1.26
    environment:
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
      KC_DB_USERNAME: iam
      KC_DB_PASSWORD: iam123456
      KC_DB_URL_HOST: 127.0.0.1
      KC_DB_URL_PORT: 30000
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    depends_on:
      - postgres
    ports:
      - "8558:8080"
volumes:
  postgres-db:
    driver: local
  postgres-user:
    driver: local
 